table tab_ordem
	lineageTag: 6a5cd63d-5818-45ee-b6a7-54fd83dd7075

	column Tipo
		dataType: string
		lineageTag: 2e17087d-be3a-48b8-ad1c-988cea25921f
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Ordem
		dataType: int64
		formatString: 0
		lineageTag: a39b442f-0c68-4622-84ce-1f9d140e7e93
		summarizeBy: none
		sourceColumn: Ordem

		annotation SummarizationSetBy = Automatic

	partition tab_ordem-6e1e2da0-bc64-44cd-8d56-835bf60e9471 = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcirKz6tKVdJRMlSK1YlWCihKLEkE8ozAPP/SonwgxxjMcclMzE3MKwGpNVGKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Tipo = _t, Ordem = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Tipo", type text}, {"Ordem", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

