table TAB_DePara
	lineageTag: 2691eae0-8738-448e-84e8-1181ebb5369c

	column Codigo
		dataType: int64
		formatString: 0
		lineageTag: 20e94436-b156-40f0-8d67-141f10b5bc3b
		summarizeBy: none
		sourceColumn: Codigo

		annotation SummarizationSetBy = Automatic

	column Grupo
		dataType: string
		lineageTag: bb20f00b-6324-40bd-b0ce-da8b3ad3a4a8
		summarizeBy: none
		sourceColumn: Grupo

		annotation SummarizationSetBy = Automatic

	column Consultor
		dataType: string
		lineageTag: cd839f69-2192-4e78-9011-192e1e646b5a
		summarizeBy: none
		sourceColumn: Consultor

		annotation SummarizationSetBy = Automatic

	column Gerente
		dataType: string
		lineageTag: 41e1bf0c-f0f9-408d-bd51-88d0c9c72218
		summarizeBy: none
		sourceColumn: Gerente

		annotation SummarizationSetBy = Automatic

	partition TAB_DePara = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dVNBbttADPwK4XMOthvZ0pHapSUGq12DKwmwgxxyyCGHooGD/r8rpUDLgL4J0MwsZ4Z8ft7s9o/Nbrd52HS33x+/YPnCiOBQUuDy0aK0KSP4BGdBn8r/8fXn++3tc/PysNLrQ/2NPqbICAM6svDNdq/w5DkQewIMM2XICz9Dj/FKwXjtWCl2Ty3JCEMS5AxOpqvBqTSHYyfsoU2zOZ62E1BwladsKDffwBNGCOlsYivtWyjiuMQkjNHKtdbakjoSOJMQC1o1HBQ8l7l76EkiRl9ypVyoJVuyLOt8RuRhcZ05zNZL9b+X9n/35cxiej4eFbSVKaZVl/Ioxih1tVUEV1bDERTPlnqtwR7nUmsZfeRowQ+NhsvkmMIFXAqTc1wWQjq75UoRyXcoHk4k97qofihCx7n4iARdGkoV/m60zVaP+DQFXuK918Rhp+DFBhZ5gnK78zLacsczht5ar0a3uO4hnLCblnWxqtSeBr4iha+jtdR18Zl9pMt63MXP//iXPw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Codigo = _t, Grupo = _t, Consultor = _t, Gerente = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Codigo", Int64.Type}, {"Grupo", type text}, {"Consultor", type text}, {"Gerente", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

