table tb_auto_pan_too_seguros
	lineageTag: a7c7cf82-d388-4e61-8e07-755dd76c375a

	measure 'qtd_contrato v2' =
			
			CALCULATE(
			    DISTINCTCOUNTNOBLANK(tb_auto_pan_too_seguros[num_proposta])
			)
		formatString: #,0
		lineageTag: 74fb4b9b-da22-42fc-8a12-5338d5e3580b

	measure '% Aproveitamento v2' =
			
			DIVIDE(
			    sum(tb_auto_pan_too_seguros[qtde_seguro])
			    , sum(tb_auto_pan_too_seguros[qtd_potencial_lake])
			    , BLANK()
			)
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: de959cc7-e455-429e-b2e9-bc0bf22f63fe

	measure 'TM Emprestimo v2' =
			
			DIVIDE(
			    CALCULATE(
			        sum(tb_auto_pan_too_seguros[val_producao])
			    )
			    , [qtd_contrato v2]
			    , BLANK()
			)
		formatString: #,0.0
		lineageTag: 5ad2154d-4e8c-4a2e-a2bd-f960e96a0d4c

	measure 'TM Seguros v2' =
			
			DIVIDE(
			   sum(tb_auto_pan_too_seguros[valor_seguro])
			    , sum(tb_auto_pan_too_seguros[qtde_seguro])
			    , BLANK()
			)
		formatString: #,0.0
		lineageTag: 4700e73a-ed2d-4de3-a276-2d3b41db4bc1

	measure qtd_emitido = Count(tb_auto_pan_too_seguros[sql_DATA_EMISSAO_AUTO_PAN])
		formatString: #,0
		lineageTag: c97291f4-f8c9-42f5-871b-a9114b2277e5

	measure '% Potencial' =
			
			DIVIDE(
			    sum(tb_auto_pan_too_seguros[qtd_potencial_lake])
			    , [qtd_contrato v2]
			    , BLANK()
			)
		formatString: 0%;-0%;0%
		lineageTag: 1212126a-bed3-48e7-9bb8-6d9817ded38e

	column num_proposta
		dataType: string
		lineageTag: de0ce193-f4a7-4569-8302-22b102f03f15
		summarizeBy: none
		sourceColumn: num_proposta

		annotation SummarizationSetBy = Automatic

	column plataforma
		dataType: string
		lineageTag: 980f3e15-3ba7-4050-9dbc-456992b34a38
		summarizeBy: none
		sourceColumn: plataforma

		annotation SummarizationSetBy = Automatic

	column cod_produto
		dataType: string
		lineageTag: 726c83b6-eb12-4bcf-9921-738ddd40baf8
		summarizeBy: none
		sourceColumn: cod_produto

		annotation SummarizationSetBy = Automatic

	column produto
		dataType: string
		lineageTag: 629bc539-9383-4875-9620-9d6a130611a4
		summarizeBy: none
		sourceColumn: produto

		annotation SummarizationSetBy = Automatic

	column cod_operador
		dataType: string
		lineageTag: bdb76a69-4486-4607-beea-a39823a75e32
		summarizeBy: none
		sourceColumn: cod_operador

		annotation SummarizationSetBy = Automatic

	column val_financiado
		dataType: double
		formatString: #,0
		lineageTag: 74765532-23e4-4f3c-81c1-336155422ecb
		summarizeBy: sum
		sourceColumn: val_financiado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column situacao_proposta
		dataType: string
		lineageTag: 6b628621-3499-4832-a34e-a5d2310a97ec
		summarizeBy: none
		sourceColumn: situacao_proposta

		annotation SummarizationSetBy = Automatic

	column data_situacao
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6b0fe8b2-e77f-444f-ad14-0c15d6a5bff4
		summarizeBy: none
		sourceColumn: data_situacao

		variation Variation
			isDefault
			relationship: 8327d32a-b790-4fc1-b4d9-98c201d7fb86
			defaultHierarchy: LocalDateTable_dce17838-a804-44db-b0ed-a95125da1927.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column nome_loja_prop
		dataType: string
		lineageTag: 105e151e-f527-4dbb-8754-b330c0a0844e
		summarizeBy: none
		sourceColumn: nome_loja_prop

		annotation SummarizationSetBy = Automatic

	column desc_unidade_prop
		dataType: string
		lineageTag: 11a0dfdd-f3c5-4cbf-9db5-6106e89b4d9c
		summarizeBy: none
		sourceColumn: desc_unidade_prop

		annotation SummarizationSetBy = Automatic

	column regional_prop
		dataType: string
		lineageTag: de4a890a-7446-468c-bfb9-684b2777b67e
		summarizeBy: none
		sourceColumn: regional_prop

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: cb7e350b-2fc9-4b2f-b874-4769a296e4e3
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	column subcanal
		dataType: string
		lineageTag: 9354ad6f-0aaa-4921-8839-38add0b9abf5
		summarizeBy: none
		sourceColumn: subcanal

		annotation SummarizationSetBy = Automatic

	column subcanal_tratado
		dataType: string
		lineageTag: 4cfb02a3-5a53-4c1b-bffe-291020e06697
		summarizeBy: none
		sourceColumn: subcanal_tratado

		annotation SummarizationSetBy = Automatic

	column val_producao
		dataType: double
		formatString: #,0
		lineageTag: 198a3fa0-1e24-470c-a0ec-10e9d0e64e91
		summarizeBy: sum
		sourceColumn: val_producao

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column valor_seguro
		dataType: double
		formatString: #,0
		lineageTag: 262c2246-b66c-4132-bb28-331a580f4748
		summarizeBy: sum
		sourceColumn: valor_seguro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column ds_tipo_produto
		dataType: string
		lineageTag: e3cb2a98-06a3-4f7f-9111-39dab0323dc0
		summarizeBy: none
		sourceColumn: ds_tipo_produto

		annotation SummarizationSetBy = Automatic

	column qtde_seguro
		dataType: int64
		formatString: #,0
		lineageTag: 9ea0e68e-c633-4342-844f-ca72384d494f
		summarizeBy: sum
		sourceColumn: qtde_seguro

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column sql_POTENCIAL_AUTO_PAN
		dataType: int64
		formatString: 0
		lineageTag: 5229cef6-c8ed-41d0-b9c9-111a6a424ff5
		summarizeBy: sum
		sourceColumn: sql_POTENCIAL_AUTO_PAN

		annotation SummarizationSetBy = Automatic

	column sql_DATA_EMISSAO_AUTO_PAN
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0332060a-ffaf-4bdf-a065-50ad2337c69f
		summarizeBy: none
		sourceColumn: sql_DATA_EMISSAO_AUTO_PAN

		variation Variation
			isDefault
			relationship: e7c60980-5c98-4d2e-8dbd-41b31e4442bf
			defaultHierarchy: LocalDateTable_d8249b44-7ad4-4b83-a1a5-a886dcce5da5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sql_ds_faixa_idade
		dataType: string
		lineageTag: c113a396-cb03-407e-88a2-d9c11999874b
		summarizeBy: none
		sourceColumn: sql_ds_faixa_idade

		annotation SummarizationSetBy = Automatic

	column ds_consolidador
		dataType: string
		lineageTag: e6720477-887f-4237-afdd-511ee9c0edd9
		summarizeBy: none
		sourceColumn: ds_consolidador

		annotation SummarizationSetBy = Automatic

	column AnoMes
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 4837c99d-3a8d-450a-8b86-a85344f42859
		summarizeBy: none
		sourceColumn: AnoMes

		variation Variation
			isDefault
			relationship: aaef4ee9-299e-4fa7-aade-ae56d2f3ca67
			defaultHierarchy: LocalDateTable_b3a3de30-02e6-40ea-a357-4a48f3c987b9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column qtd_potencial_lake
		dataType: int64
		formatString: #,0
		lineageTag: 9d7a9967-dca5-495e-bb13-597c8d864c58
		summarizeBy: sum
		sourceColumn: qtd_potencial_lake

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column subcanal_tratado2
		dataType: string
		lineageTag: eb215396-422a-4e4f-9054-468612dffe3a
		summarizeBy: none
		sourceColumn: subcanal_tratado2

		annotation SummarizationSetBy = Automatic

	column nome_operador
		dataType: string
		lineageTag: b8b131ff-cb61-4a0b-bb48-02b502cc6eb7
		summarizeBy: none
		sourceColumn: nome_operador

		annotation SummarizationSetBy = Automatic

	column dt_carga
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3aed9356-9bb6-4754-b5c0-2481387410d0
		summarizeBy: none
		sourceColumn: dt_carga

		variation Variation
			isDefault
			relationship: d1695947-647c-4507-ae4a-80a47fb27361
			defaultHierarchy: LocalDateTable_3fe6bffa-2b2e-4b8a-bce8-d280d6da9970.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition tb_auto_pan_too_seguros = m
		mode: import
		source = ```
				let
				    Fonte = AmazonAthena.Databases("athena", null),
				    AwsDataCatalog_Database = Fonte{[Name="AwsDataCatalog",Kind="Database"]}[Data],
				    db_banco_pan_analytics_Schema = AwsDataCatalog_Database{[Name="db_banco_pan_analytics",Kind="Schema"]}[Data],
				    tb_auto_pan_too_seguros_Table = db_banco_pan_analytics_Schema{[Name="tb_auto_pan_too_seguros",Kind="Table"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(tb_auto_pan_too_seguros_Table, let latest = List.Max(tb_auto_pan_too_seguros_Table[dt_carga]) in each [dt_carga] = latest),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas Filtradas", "ds_tipo_produto", each if Text.Contains([produto], "TROCO") then "Troco" else "Boleto"),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Coluna Condicional Adicionada", "qtde_seguro", each if [valor_seguro] > 0 then 1 else 0),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Coluna Condicional Adicionada1", "ds_consolidador", each if Text.Contains([produto], "MOTOS") then "MOTOS" else "LEVES"),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Coluna Condicional Adicionada2", {"num_proposta"}, REL_Veiculo_Producao, {"COD_CONTRATO"}, "REL_Veiculo_Producao", JoinKind.LeftOuter),
				    #"REL_Veiculo_Producao Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "REL_Veiculo_Producao", {"POTENCIAL_AUTO_PAN", "DATA_EMISSAO_AUTO_PAN", "ds_faixa_idade"}, {"REL_Veiculo_Producao.POTENCIAL_AUTO_PAN", "REL_Veiculo_Producao.DATA_EMISSAO_AUTO_PAN", "REL_Veiculo_Producao.ds_faixa_idade"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"REL_Veiculo_Producao Expandido",{{"REL_Veiculo_Producao.POTENCIAL_AUTO_PAN", "sql_POTENCIAL_AUTO_PAN"}, {"REL_Veiculo_Producao.DATA_EMISSAO_AUTO_PAN", "sql_DATA_EMISSAO_AUTO_PAN"}, {"REL_Veiculo_Producao.ds_faixa_idade", "sql_ds_faixa_idade"}}),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Colunas Renomeadas", "data_situacao", "data_situacao - Copiar"),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Duplicada",{{"data_situacao - Copiar", "AnoMes"}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Colunas Renomeadas1",null,"6. Não Informado",Replacer.ReplaceValue,{"sql_ds_faixa_idade"}),
				    #"Personalização Adicionada2" = Table.AddColumn(#"Valor Substituído", "qtd_potencial_lake", each if [qtde_seguro] = 1 then 1
				else 
				if [data_situacao] >= #date(2026, 5, 1) 
				then 
						if [ds_tipo_produto] = "Troco" 
				           or [sql_ds_faixa_idade] = "5. Acima de 60" 
						then 0
				        else 1
				else
					if [ds_tipo_produto] = "Troco" 
				           or [sql_ds_faixa_idade] = "5. Acima de 60" 
				           or [sql_ds_faixa_idade] = "6. Não Informado"
				    then 0
				else 1)
				in
				    #"Personalização Adicionada2"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

