table REL_Habitacional_Base_Sintetica
	lineageTag: 265d8954-dab3-44ec-97c9-60fe49f036e4

	measure 'ticket medio Contratos' = IFERROR(sum (REL_Habitacional_Base_Sintetica[vlPremio]) / sum (REL_Habitacional_Base_Sintetica[qtContratosCarteira]),0)
		formatString: #,0
		lineageTag: 316436f2-4293-4430-bb9e-9c8fedc267fc

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'ticket medio Contratos Novos' = IFERROR(sum (REL_Habitacional_Base_Sintetica[vlPremioContratosNovos]) / sum (REL_Habitacional_Base_Sintetica[qtContratosNovos]),0)
		formatString: #,0
		lineageTag: 8d7d44d6-8d87-4ff7-bb86-32be558dd545

		annotation PBI_FormatHint = {"isDecimal":true}

	measure qtContratosRetroativos = sum(REL_Habitacional_Base_Sintetica[qtContratosNovos]) - sum('REL_Habitacional_Base_Sintetica (2)'[qtContratosNovos])
		formatString: 0
		lineageTag: f73571ad-cd99-4f43-9d27-8c60fa36eb22

	measure 'qt Expectativa x Arquivo CEF' = sum (REL_Habitacional_Base_Sintetica[qtContratosCarteira]) - sum (REL_Habitacional_Base_Sintetica[qtContratosExpectativa])
		formatString: #,0
		lineageTag: 3ad458fb-9ce0-455c-9c76-7615421237d3

		annotation PBI_FormatHint = {"isDecimal":true}

	measure '% Expectativa x Arquivo CEF' = (sum (REL_Habitacional_Base_Sintetica[qtContratosCarteira]) - sum (REL_Habitacional_Base_Sintetica[qtContratosExpectativa])) / sum (REL_Habitacional_Base_Sintetica[qtContratosCarteira])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2edcaff3-9d45-4586-ba9b-c74b1bd0e32c

	measure 'vl Crecimento MoM Carteira' = ```
			
				VAR __PREV_MONTH =
					CALCULATE(
						sum([vlPremio]),
						DATEADD('REL_Habitacional_Base_Sintetica'[dtCompetencia].[Date], -1, MONTH)
					)
				RETURN
					DIVIDE(sum(REL_Habitacional_Base_Sintetica[vlPremio]) - __PREV_MONTH, __PREV_MONTH)
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 4a37f398-d5c0-45a8-8bcf-c568a00b2f88

	measure 'qt Crecimento MoM Carteira' = ```
			
				VAR __PREV_MONTH =
					CALCULATE(
						sum([qtContratosCarteira]),
						DATEADD('REL_Habitacional_Base_Sintetica'[dtCompetencia].[Date], -1, MONTH)
					)
				RETURN
					DIVIDE(sum(REL_Habitacional_Base_Sintetica[qtContratosCarteira]) - __PREV_MONTH, __PREV_MONTH)
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: acceedbd-be60-4ab2-8b04-543ccf49ba80

	measure 'qt Crecimento MoM Contratos Novos' = ```
			
				VAR __PREV_MONTH =
					CALCULATE(
						sum([qtContratosNovos]),
						DATEADD('REL_Habitacional_Base_Sintetica'[dtCompetencia].[Date], -1, MONTH)
					)
				RETURN
					DIVIDE(sum(REL_Habitacional_Base_Sintetica[qtContratosNovos]) - __PREV_MONTH, __PREV_MONTH)
			```
		formatString: #,0.0%;-#,0.0%;#,0.0%
		lineageTag: 31a2fb2e-5e32-4bc8-a0eb-55311189550a

	measure 'Média de qtContratosNovos por Trimestre' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('REL_Habitacional_Base_Sintetica'[dtCompetencia].[Trimestre])),
				CALCULATE(SUM('REL_Habitacional_Base_Sintetica'[qtContratosNovos]))
			)
		formatString: #,0
		lineageTag: 946890b5-7293-4a4e-99de-dd29672ed8a0

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "AveragePerCategory"
				}

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Média de qtContratosNovos por Trimestre 2' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('REL_Habitacional_Base_Sintetica'[dtCompetencia].[Trimestre])),
				CALCULATE(SUM('REL_Habitacional_Base_Sintetica'[qtContratosNovos]))
			)
		formatString: #,0
		lineageTag: 83f2f12e-4a31-41af-8a3c-23f8971106d3

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "AveragePerCategory"
				}

		annotation PBI_FormatHint = {"isDecimal":true}

	measure qtContratosMes = sum(REL_Habitacional_Base_Sintetica[qtContratosCarteira]) - sum(REL_Habitacional_Base_Sintetica[qtContratosNovos])
		formatString: #,0
		lineageTag: d11e6479-0f04-491d-97fe-b3e70d1e216e

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'qtContratoCarteira Last Date' = ```
			
			CALCULATE(
			    sum(REL_Habitacional_Base_Sintetica[qtContratosCarteira]),
			    LASTDATE(REL_Habitacional_Base_Sintetica[dtCompetencia])   
			        )
			```
		formatString: #,0
		lineageTag: 26a4d5ff-5147-4a8a-a50c-d03973b5b3d2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'qtClientesCarteira Last Date' = ```
			
			CALCULATE(
			    sum(REL_Habitacional_Base_Sintetica[qtClientes]),
			    LASTDATE(REL_Habitacional_Base_Sintetica[dtCompetencia])   
			        )
			```
		formatString: #,0
		lineageTag: 3e8eb00d-ace2-454c-ba42-938fd7acdc78

		changedProperty = FormatString

	measure vlPremio_Last_Date = ```
			
			CALCULATE(
			     sum(REL_Habitacional_Base_Sintetica[vlPremio])
			    ,LASTDATE(REL_Habitacional_Base_Sintetica[dtCompetencia])   
			)
			```
		formatString: #,0
		lineageTag: 24b28a59-e0cf-49d6-ab3a-e066b85fb90c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure ticket_medio_primeira_parcela =
			
			DIVIDE(
			     sum(REL_Habitacional_Base_Sintetica[vlPremioPrimeiraParcela])
			    ,sum(REL_Habitacional_Base_Sintetica[qtContratosNovos])
			    ,BLANK()
			)
		formatString: #,0
		lineageTag: ac271455-49f8-4759-89e4-00ea4a277046

		annotation PBI_FormatHint = {"isDecimal":true}

	column id
		dataType: int64
		formatString: 0
		lineageTag: 5026ea2d-9b04-4f1d-8c1d-27819679d380
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column dtCompetencia
		dataType: dateTime
		formatString: Short Date
		lineageTag: f0bc5b8f-2fd8-4980-83b8-679bd7ec4de4
		summarizeBy: none
		sourceColumn: dtCompetencia

		variation Variation
			isDefault
			relationship: b4b81a37-a771-4d2d-abac-3cff3ce99918
			defaultHierarchy: LocalDateTable_b35e839b-2d73-4488-9627-91e75f7ddb1d.'Hierarquia de Datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column cdEstipulante
		dataType: int64
		formatString: 0
		lineageTag: 6bd48025-ceb2-4377-b9a2-779d05227d40
		summarizeBy: sum
		sourceColumn: cdEstipulante

		annotation SummarizationSetBy = Automatic

	column dtContrato
		dataType: string
		lineageTag: 3eac9233-0b8e-40e0-a93f-6963bae0d51c
		summarizeBy: none
		sourceColumn: dtContrato

		annotation SummarizationSetBy = Automatic

	column vlPremio
		dataType: double
		formatString: #,0
		lineageTag: bcbc4d3f-fcbd-494c-950f-9d52e9526393
		summarizeBy: sum
		sourceColumn: vlPremio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column vlPremioMIP
		dataType: double
		formatString: #,0
		lineageTag: db26727a-48d7-4078-8aa0-b2687ad367d4
		summarizeBy: sum
		sourceColumn: vlPremioMIP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column vlPremioDFI
		dataType: double
		formatString: #,0
		lineageTag: b609df44-851d-49a1-bccc-1f9fd04a1a13
		summarizeBy: sum
		sourceColumn: vlPremioDFI

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column vlPremioRCC
		dataType: double
		formatString: #,0
		lineageTag: e8fbda5f-1ed4-4a2e-8d3a-67cb855decef
		summarizeBy: sum
		sourceColumn: vlPremioRCC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column qtContratosNovos
		dataType: int64
		formatString: #,0
		lineageTag: 854fff3b-bd7a-4966-98db-e8758d77de36
		summarizeBy: sum
		sourceColumn: qtContratosNovos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column qtClientes
		dataType: int64
		formatString: #,0
		lineageTag: e14990ae-94ce-4a27-84b9-f36e3a61ae70
		summarizeBy: sum
		sourceColumn: qtClientes

		annotation SummarizationSetBy = Automatic

	column qtContratosCarteira
		dataType: int64
		formatString: #,0
		lineageTag: 8a039fd0-7f79-4310-a701-920e866c952f
		summarizeBy: sum
		sourceColumn: qtContratosCarteira

		annotation SummarizationSetBy = Automatic

	column vlAtrasadoDevolver
		dataType: double
		lineageTag: deace8c5-e0df-4092-b3d4-eefb4f5dbb57
		summarizeBy: sum
		sourceColumn: vlAtrasadoDevolver

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlAtrasadoMIPCancelamento
		dataType: double
		lineageTag: f6d3cd32-fb29-4a20-9b70-f5f41b8e1243
		summarizeBy: sum
		sourceColumn: vlAtrasadoMIPCancelamento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlAtrasadoDIFCancelamento
		dataType: double
		lineageTag: 82e9b289-14b5-472e-b37f-ea66b66474f7
		summarizeBy: sum
		sourceColumn: vlAtrasadoDIFCancelamento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column vlAtrasadoRCCCancelamento
		dataType: double
		lineageTag: 52d79205-44ca-4ac2-948e-53b8a8f1f00d
		summarizeBy: sum
		sourceColumn: vlAtrasadoRCCCancelamento

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qtContratosCancelados
		dataType: int64
		formatString: 0
		lineageTag: f539379f-18d5-42ca-9fcf-d424e282b465
		summarizeBy: sum
		sourceColumn: qtContratosCancelados

		annotation SummarizationSetBy = Automatic

	column vlPremioContratosNovos
		dataType: double
		formatString: #,0
		lineageTag: 44a671f8-5cc0-4bc6-ae56-ac5cc57ab0b5
		summarizeBy: sum
		sourceColumn: vlPremioContratosNovos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column dtAtualizacao
		dataType: dateTime
		formatString: General Date
		lineageTag: b34ded59-9ef7-404d-8dc4-1f24cc50cfec
		summarizeBy: none
		sourceColumn: dtAtualizacao

		variation Variation
			isDefault
			relationship: fe9561f3-9934-41fd-848b-fd6b17f81bc7
			defaultHierarchy: LocalDateTable_6547a8cd-92d3-45a8-941b-1bd01fede98c.'Hierarquia de Datas'

		annotation SummarizationSetBy = Automatic

	column 'Canal Venda'
		dataType: string
		lineageTag: 89d49f84-9460-408b-a4f4-6d63ccf6cd93
		summarizeBy: none
		sourceColumn: Canal Venda

		annotation SummarizationSetBy = Automatic

	column qtContratosExpectativa
		dataType: double
		formatString: #,0
		lineageTag: 9947a8c6-aba3-4864-902c-994d22a6cbc3
		summarizeBy: sum
		sourceColumn: qtContratosExpectativa

		annotation SummarizationSetBy = Automatic

	column 'Canal Venda Base Sintetica'
		dataType: string
		lineageTag: 4e9f5ffc-ef49-4adc-a018-c44b04c107ae
		summarizeBy: none
		sourceColumn: Canal Venda Base Sintetica

		annotation SummarizationSetBy = Automatic

	column ChaveMetaSintetica
		dataType: string
		lineageTag: 5bdee8ab-1909-45b2-8b68-e95f10bcb301
		summarizeBy: none
		sourceColumn: ChaveMetaSintetica

		annotation SummarizationSetBy = Automatic

	column 'Regra Data'
		dataType: string
		lineageTag: a9ec54a9-157f-4777-9947-7c7447a5aefc
		summarizeBy: none
		sourceColumn: Regra Data

		annotation SummarizationSetBy = Automatic

	column qtContratosNovosMes
		dataType: int64
		formatString: 0
		lineageTag: b1d18420-0717-40c2-8a81-91b01eea8fc4
		summarizeBy: sum
		sourceColumn: qtContratosNovosMes

		annotation SummarizationSetBy = Automatic

	column ChaveEntreBasesSinteticas
		dataType: string
		lineageTag: d027e875-db48-4127-9f46-e1aa935c78b1
		summarizeBy: none
		sourceColumn: ChaveEntreBasesSinteticas

		annotation SummarizationSetBy = Automatic

	column País
		dataType: string
		lineageTag: 8824f2df-1003-4db0-b703-0facfbf5b1db
		summarizeBy: none
		sourceColumn: País

		annotation SummarizationSetBy = Automatic

	column cdUF
		dataType: string
		lineageTag: aeabffb3-f2e9-4f18-aaa5-116a7953d6ad
		summarizeBy: none
		sourceColumn: cdUF

		annotation SummarizationSetBy = Automatic

	column dtCompetenciaChave
		dataType: string
		lineageTag: 7559c7b3-f52d-44f0-924a-d5448c5a95b9
		summarizeBy: none
		sourceColumn: dtCompetenciaChave

		annotation SummarizationSetBy = Automatic

	column 'chave venda x sintetica'
		dataType: string
		lineageTag: c37bd7ef-319c-40e7-9b62-ccb77d542812
		summarizeBy: none
		sourceColumn: chave venda x sintetica

		annotation SummarizationSetBy = Automatic

	column vlPremioPrimeiraParcela
		dataType: double
		formatString: #,0
		lineageTag: 7866f119-6e45-48f7-8588-96d104273781
		summarizeBy: sum
		sourceColumn: vlPremioPrimeiraParcela

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column dsCidade
		dataType: string
		lineageTag: 0f28043a-f968-41c5-b136-59bb100d0b5f
		summarizeBy: none
		sourceColumn: dsCidade

		annotation SummarizationSetBy = Automatic

	column Chave_Nova_Safra
		dataType: string
		lineageTag: a21d6b23-aeb8-4660-8ac6-c8b94abfcc23
		summarizeBy: none
		sourceColumn: Chave_Nova_Safra

		annotation SummarizationSetBy = Automatic

	column fl_legado_nova_comissao
		dataType: string
		lineageTag: df02e6d5-931a-4eb6-a676-ed995aae5eda
		summarizeBy: none
		sourceColumn: fl_legado_nova_comissao

		annotation SummarizationSetBy = Automatic

	column dsCidadeAgrupada
		dataType: string
		lineageTag: 89260754-3c6c-496c-91d3-561c7f854b14
		summarizeBy: none
		sourceColumn: dsCidadeAgrupada

		annotation SummarizationSetBy = Automatic

	partition REL_Habitacional_Base_Sintetica-153ffdf7-5613-40ce-aa45-f558754a21de = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("sql-sandbox", "CONTROLADORIA"),
				    dbo_REL_Habitacional_Base_Sintetica = Fonte{[Schema="dbo",Item="REL_Habitacional_Base_Sintetica"]}[Data],
				    #"Coluna Condicional Adicionada" = Table.AddColumn(dbo_REL_Habitacional_Base_Sintetica, "Personalizar", each if [cdEstipulante] = 6207 then "MCMV" else "BALCÃO"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Condicional Adicionada",{{"Personalizar", "Canal Venda"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"dtCompetencia", type date}}),
				    #"Coluna Duplicada" = Table.DuplicateColumn(#"Tipo Alterado", "dtCompetencia", "dtCompetencia - Copiar"),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Coluna Duplicada",{{"dtCompetencia - Copiar", "dtCompetenciaChave"}}),
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Colunas Renomeadas1", "Canal Venda Base Sintetica", each if [cdEstipulante] = 6207 then "MCMV / CASA VERDE E AMARELA" else "BALCAO"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada1",{{"dtCompetenciaChave", type text}}),
				    #"Coluna Condicional Adicionada2" = Table.AddColumn(#"Tipo Alterado1", "Personalizar", each if [dtCompetencia] <= #date(2018, 12, 1) then "UNIFICADO" else [Canal Venda Base Sintetica]),
				    #"Colunas Renomeadas2" = Table.RenameColumns(#"Coluna Condicional Adicionada2",{{"Personalizar", "Regra Data"}}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Colunas Renomeadas2", "ChaveMetaSintetica", each Text.Combine({[dtCompetenciaChave], [Regra Data]}, ""), type text),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Coluna Mesclada Inserida", "ChaveEntreBasesSinteticas", each Text.Combine({[dtCompetenciaChave], [Regra Data], [cdUF]}, ""), type text),
				    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Mesclada Inserida1", "País", each "BRASIL"),
				    #"Coluna Duplicada1" = Table.DuplicateColumn(#"Personalização Adicionada", "País", "País - Copiar"),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna Duplicada1",{"País - Copiar"}),
				    #"Coluna Duplicada2" = Table.DuplicateColumn(#"Colunas Removidas", "dtCompetenciaChave", "dtCompetenciaChave - Copiar"),
				    #"Coluna Duplicada3" = Table.DuplicateColumn(#"Coluna Duplicada2", "cdUF", "cdUF - Copiar"),
				    #"Colunas Mescladas" = Table.CombineColumns(#"Coluna Duplicada3",{"dtCompetenciaChave - Copiar", "cdUF - Copiar"},Combiner.CombineTextByDelimiter(";", QuoteStyle.None),"chave venda x sintetica"),
				    #"Coluna Mesclada Inserida2" = Table.AddColumn(#"Colunas Mescladas", "Chave_Nova_Safra", each Text.Combine({Text.From([dtCompetencia], "pt-BR"), [Canal Venda], [cdUF]}, "|"), type text),
				    #"Personalização Adicionada1" = Table.AddColumn(#"Coluna Mesclada Inserida2", "fl_legado_nova_comissao", each if [dtContrato] = null then "Data Inválida" else if Date.From([dtContrato]) <= #date(2024, 8, 1) then "Legado" else "Nova Comissão"),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"fl_legado_nova_comissao", type text}})
				in
				    #"Tipo Alterado2"

	annotation PBI_QueryRelationships = {"columnCount":28,"keyColumnNames":["id"],"queryRelationships":[],"columnIdentities":["Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{id,0}","Section1/REL_Habitacional_Base_Sintetica/Tipo Alterado.{dtCompetencia,1}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{cdEstipulante,2}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{dtContrato,3}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{cdUF,4}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremio,5}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremioMIP,6}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremioDFI,7}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremioRCC,8}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosNovos,9}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtClientes,10}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosCarteira,11}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlAtrasadoDevolver,12}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlAtrasadoMIPCancelamento,13}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlAtrasadoDIFCancelamento,14}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlAtrasadoRCCCancelamento,15}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosCancelados,16}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremioContratosNovos,17}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosExpectativa,18}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosNovosMes,19}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{dtAtualizacao,20}","Section1/REL_Habitacional_Base_Sintetica/Coluna Condicional Adicionada.{Personalizar,21}","Section1/REL_Habitacional_Base_Sintetica/Tipo Alterado1.{dtCompetenciaChave,22}","Section1/REL_Habitacional_Base_Sintetica/Coluna Condicional Adicionada1.{Canal Venda Base Sintetica,23}","Section1/REL_Habitacional_Base_Sintetica/Coluna Condicional Adicionada2.{Personalizar,24}","Section1/REL_Habitacional_Base_Sintetica/Coluna Mesclada Inserida.{ChaveMetaSintetica,25}","Section1/REL_Habitacional_Base_Sintetica/Coluna Mesclada Inserida1.{ChaveEntreBasesSinteticas,26}","Section1/REL_Habitacional_Base_Sintetica/Personalização Adicionada.{País,27}"],"ColumnCount":28,"KeyColumnNames":["id"],"ColumnIdentities":["Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{id,0}","Section1/REL_Habitacional_Base_Sintetica/Tipo Alterado.{dtCompetencia,1}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{cdEstipulante,2}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{dtContrato,3}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{cdUF,4}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremio,5}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremioMIP,6}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremioDFI,7}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremioRCC,8}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosNovos,9}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtClientes,10}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosCarteira,11}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlAtrasadoDevolver,12}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlAtrasadoMIPCancelamento,13}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlAtrasadoDIFCancelamento,14}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlAtrasadoRCCCancelamento,15}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosCancelados,16}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{vlPremioContratosNovos,17}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosExpectativa,18}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{qtContratosNovosMes,19}","Server.Database\\/2/SQL/toovdbp01;CONTROLADORIA/dbo/REL_Habitacional_Base_Sintetica.{dtAtualizacao,20}","Section1/REL_Habitacional_Base_Sintetica/Coluna Condicional Adicionada.{Personalizar,21}","Section1/REL_Habitacional_Base_Sintetica/Tipo Alterado1.{dtCompetenciaChave,22}","Section1/REL_Habitacional_Base_Sintetica/Coluna Condicional Adicionada1.{Canal Venda Base Sintetica,23}","Section1/REL_Habitacional_Base_Sintetica/Coluna Condicional Adicionada2.{Personalizar,24}","Section1/REL_Habitacional_Base_Sintetica/Coluna Mesclada Inserida.{ChaveMetaSintetica,25}","Section1/REL_Habitacional_Base_Sintetica/Coluna Mesclada Inserida1.{ChaveEntreBasesSinteticas,26}","Section1/REL_Habitacional_Base_Sintetica/Personalização Adicionada.{País,27}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navegação

