table TAB_Grupo_Ativacao
	lineageTag: b7488207-d947-41ae-855d-53f334f575b6

	column Chave_Grupo_CCA_Vendas_Ativacao
		dataType: string
		lineageTag: eb7cc267-af2d-4337-9e2e-bbc83056caac
		summarizeBy: none
		sourceColumn: Chave_Grupo_CCA_Vendas_Ativacao

		annotation SummarizationSetBy = Automatic

	column grupo_cca
		dataType: string
		lineageTag: 4a7ba2d3-72a1-44e3-97cb-dd18a8c65eba
		summarizeBy: none
		sourceColumn: grupo_cca

		annotation SummarizationSetBy = Automatic

	partition TAB_Grupo_Ativacao = m
		mode: import
		source =
				let
				    Fonte = REL_Habitacional_Zoho_Visitas,
				    #"Outras Colunas Removidas" = Table.SelectColumns(Fonte,{"Chave_Grupo_CCA_Vendas_Ativacao", "grupo_cca"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas")
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

